name: Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Tectonic Files
      id: cache-tectonic
      uses: actions/cache@v1
      with: 
        path: $HOME/.cache/Tectonic
        key: ${{ runner.os }}-tectonic
      
    - name: LaTeX compilation
      uses: lihram/tectonic-nix@v1.0-alpha
      with:
        file: report/master.tex
    
    - name: Upload master.pdf
      uses: actions/upload-artifact@v1
      with:
        name: report.pdf
        path: report/master.pdf
